networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    platform: linux/arm64
    ports:
      - "8005:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/arm64
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    platform: linux/arm64
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      mysql:
        condition: service_healthy

