<?php

return [
    'Henglai' => [
        'Salesperson' => [],
        'Management' => [
            'view_project_requirements_document', 
            'view_project_evo_document',
            'view_project_vo_document',
            'view_project_foc_document',
            'view_project_foc_document',
            'view_project_requirement_document',
            'view_document',
            'view_project_sales_report',
            'view_project_report',
            'view_project_quotation_document',
            'view_project_contract_document',
            'view_project_design_work_document',
            'view_project_quotation',
        ],
        'Drafter' => [],
        'Accountant' => [
            'access_sale_calendar',
            'access_sale_report',
            'access_sale_report_dashboard',
            'create_company_kpi',
            'create_sale_report',
            'view_company_kpi_by_year',
            'view_company_kpi_list',
            'view_individual_report',
            'view_monthly_kpi',
            'view_ongoing_project',
            'view_salesperson_yearly_kpi',
            'view_yearly_kpi'
        ],
        'Customer' => [
            "create_FAQ",
            "view_project_handover_document",
            "view_project_work_order_document"
        ],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Miracle' => [
        'Salesperson' => [''],
        'Management' => [
            'create_user',
            'update_user', 
            'update_company_EVO_template', 
            'access_admin_user',
            'view_project_requirement_document',
            'view_project_requirements_document',
            'view_project_evo_document',
            'view_project_vo_document',
            'view_project_foc_document',
            'update_project',
            'view_document',
            'create_project_quotation_document',
            'delete_customer_payment',
            'view_project_settings',
            'update_project_settings',
            'view_project_quotation_document',
            'view_project_contract_document',
            'view_project_design_work_document',
            'view_project_work_order_document',
            'view_project_quotation',
        ],
        'Drafter' => [],
        'Accountant' => [
            'view_project_cover_document',
            'view_project_requirement_document',
            'view_project_quotation_document',
            'view_project_contract_document',
            'view_project_design_work_document',
            'view_project_work_order_document',
            'view_project_handover_document',
            'view_project_vo_document',
            'view_project_evo_document',
            'view_project_foc_document',
            'view_project_cancellation_document',
            'view_design_work_document',
            'view_project_requirements_document',
            'view_3D_design_document',
            'view_document',
            'view_project_quotation',
            'generate_project_handover_document',
            'create_document',
            'update_document',
            'view_project_report',
            'view__project_by_management'
        ],
        'Customer' => [
            "view_project_cover_document",
            "view_project_handover_document",
            "view_3D_design_document",
            "view_project_milestone",
            "view_project_timeline",
            "view_timeline",
            "view_customer_FAQ",
            "sign_project_handover_document_by_customer",
            "sign_project_design_work_document",
            "sign_project_contract_document",
            "create_project_quotation_document",
            "create_project_evo_document",
            "create_project_vo_document",
            "create_project_design_work_document",
            "create_project_requirement_document",
            "create_project_foc_document",
            "create_project_cancellation_document",
            "create_additional_document",
            "create_3D_design_document",
            "create_document"
        ],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => ["access_management_admin", "create_user", "update_user", "delete_user", "access_admin_user"],
    ],
    'Twp' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [
            'access_sale_calendar',
            'access_sale_report',
            'access_sale_report_dashboard',
            'create_company_kpi',
            'create_sale_report',
            'view_company_kpi_by_year',
            'view_company_kpi_list',
            'view_individual_report',
            'view_monthly_kpi',
            'view_ongoing_project',
            'view_salesperson_yearly_kpi',
            'view_yearly_kpi'
        ],
        'Customer' => [
            "view_project_work_order_document",
            "sign_project_quotation_document",
            "sign_project_vo_document",
            "sign_project_evo_document",
            "sign_project_foc_document",
            "sign_project_cancellation_document"
        ],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [
            'access_management_admin',
            'view_document_standard',
            'create_document_standard',
            'update_document_standard',
            'update_personal_quotation_template',
            'view_personal_quotation_template',
            'update_EVO_template',
            'create_EVO_template',
            'view_EVO_template',
            'update_company_quotation_template',
            'view_company_quotation_template',
            'create_company_quotation_template',
            'view_company_EVO_template',
            'update_company_EVO_template',
            'view_project_quotation_template',
            'delete_EVO_template'
        ],
    ],
    'Jream' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Paddry' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Magnum' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Xcepcion' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Metis' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Artdecor' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'BuildSpec' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Luxcraft' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Makegood' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Amp' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Tag' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Flynn' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Praxis' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Brightway' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Molecule' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Supaspace' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Tidplus' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Whst' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Optimum' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'SaltRoom' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Blackalogy' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'FiveFoot10' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ],
    'Aplus' => [
        'Salesperson' => [],
        'Management' => [],
        'Drafter' => [],
        'Accountant' => [],
        'Customer' => [],
        'SuperAdmin' => [],
        'Marketing' => [],
        'Manager' => [],
    ]
];
